apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000  # Setting nodePort to the same value as the port
  type: NodePort

